# Generated by Django 5.2.2 on 2025-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_mail_mailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='mailrecipient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
