# Generated by Django 5.2.2 on 2025-07-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_mail_attachment_mailrecipient_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='attachment',
        ),
    ]
