# Generated by Django 5.2.2 on 2025-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_activitylog_passwordhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
